version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      storybook:
        patterns:
          - "storybook"
          - "@storybook*"
      typescript:
        patterns:
          - "typescript"
          - "@types*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
