image: gitpod/workspace-full
# Command to start on workspace startup (optional)
tasks:
  - init: npm install -g lerna && yarn install
    command: yarn build
vscode:
  extensions:
    - octref.vetur@0.31.3:QHyAEoimIBiRDoL6WtEoRg==