repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.5.0 # Replace with the version of ESLint you're using
    hooks:
      - id: eslint
        args: ["--fix"] # This will make ESLint automatically fix problems when possible

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.0 # Replace with the version of Prettier you're using
    hooks:
      - id: prettier
        args: ["--write"] # This will make Prettier automatically format the files
