name: Manage releases

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write
  id-token: write # Required for OIDC

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please! 🤖
        uses: googleapis/release-please-action@5c625bfb5d1ff62eadeeb3772007f7f66fdcf071 # v4
        id: release
      - name: Checkout 🛎️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      - name: Set up NPM 🔧
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      - name: Install dependencies 🔧
        run: npm ci
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      - name: Build and publish package 🚀
        env:
          ELEMENT_PATHS: ${{ steps.release.outputs.paths_released }}
        run: |
          npm run styles && \
          for path in `echo ${ELEMENT_PATHS//,/ } | tr -d '[]"'`
          do \
          cd $path && \
          npm run build && \
          npm publish --access=public && \
          cd ../../
          done
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
